refactor(dot): updates to the `dot` script
* Remove aliases in YAML file as it fails and also is not needed.
  https://github.com/DannyBen/bashly/issues/185
* Ask for confirmation before updating system softwares.

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -2,6 +2,12 @@
 # This script was generated by bashly (https://github.com/DannyBen/bashly)
 # Modifying it manually is not recommended
 
+# :script.bash3_bouncer
+if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+  printf "bash version 4 or higher is required\n"
+  exit 1
+fi
+
 # :command.version_command
 version_command() {
   echo "$version"
@@ -12,9 +18,11 @@ dot_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot - Personal tool for managing dotfiles and packages\n"
     echo
+
   else
     printf "dot - Personal tool for managing dotfiles and packages\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -50,9 +58,11 @@ dot_mac_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot mac - update macOS related stuff\n"
     echo
+
   else
     printf "dot mac - update macOS related stuff\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -85,9 +95,11 @@ dot_link_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot link - symlink dotfiles after backing up the existing ones\n"
     echo
+
   else
     printf "dot link - symlink dotfiles after backing up the existing ones\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -115,11 +127,14 @@ dot_shell_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot shell\n"
     echo
+
     printf "  setup the default shell for the current user\n  \n  Default shell path: \"$DEFAULT_SHELL_PATH\"\n"
     echo
+
   else
     printf "dot shell - setup the default shell for the current user\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -142,9 +157,11 @@ dot_setup_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot setup - setup a new mac machine the way I like it\n"
     echo
+
   else
     printf "dot setup - setup a new mac machine the way I like it\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -167,9 +184,11 @@ dot_sync_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot sync - sync lib files with global package list\n"
     echo
+
   else
     printf "dot sync - sync lib files with global package list\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -212,9 +231,11 @@ dot_upgrade_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot upgrade - upgrade packages\n"
     echo
+
   else
     printf "dot upgrade - upgrade packages\n"
     echo
+
   fi
 
   printf "Usage:\n"
@@ -343,6 +364,7 @@ warning() {
 # :src/lib/setup.sh
 declare -a PY_NEOVIM_PACKAGES=(
   "pynvim"
+  "debugpy"
 )
 
 declare -A SYMLINKS=(
@@ -688,8 +710,16 @@ upgrade_mac() { # {{{1
   header "Upgrading macOS applications..."
   mas upgrade
 
-  header "Updating softwares..."
-  softwareupdate --install --all
+  header "Finding available software..."
+  output="$(softwareupdate --list 2>&1 > /dev/null)"
+  if [[ "$output" == "No new software available." ]]; then
+    echo "No new software available."
+  else
+    seek_confirmation "A system update is available. Do you wish to install it?"
+    if is_confirmed; then
+      softwareupdate --install --all
+    fi
+  fi
 }
 
 upgrade_neovim() { # {{{1
@@ -819,10 +849,8 @@ link() { # {{{1
 }
 
 seek_confirmation() { # {{{1
-  if [[ -n $1 ]]; then
-    warning "$1"
-  fi
-  read -r -p "$(bold "Continue? [y/n] ")" -n 1
+  warning "$1"
+  read -r -p "$(bold "[y/n] ")" -n 1
   printf "\n"
 }
 
@@ -1016,7 +1044,7 @@ dot_upgrade_command() {
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1032,7 +1060,7 @@ parse_requirements() {
   # :command.environment_variables_filter
   # :command.dependencies_filter
   # :command.command_filter
-  action=$1
+  action=${1:-}
 
   case $action in
     -*) ;;
@@ -1087,14 +1115,12 @@ parse_requirements() {
       ;;
 
   esac
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-      -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
@@ -1107,15 +1133,18 @@ parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 dot_mac_parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1132,26 +1161,25 @@ dot_mac_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="mac"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --dock | -d)
+        # :flag.conflicts
         args[--dock]=1
         shift
         ;;
 
       # :flag.case
       --settings | -s)
+        # :flag.conflicts
         args[--settings]=1
         shift
         ;;
 
-      \
-        -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
@@ -1164,15 +1192,18 @@ dot_mac_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 dot_link_parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1189,20 +1220,18 @@ dot_link_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="link"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --force | -f)
+        # :flag.conflicts
         args[--force]=1
         shift
         ;;
 
-      \
-        -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
@@ -1215,15 +1244,18 @@ dot_link_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 dot_shell_parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1240,14 +1272,12 @@ dot_shell_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="shell"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-      -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
@@ -1260,15 +1290,18 @@ dot_shell_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 dot_setup_parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1285,14 +1318,12 @@ dot_setup_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="setup"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
-      -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
@@ -1305,15 +1336,18 @@ dot_setup_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 dot_sync_parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1330,38 +1364,39 @@ dot_sync_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="sync"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --brew | -b)
+        # :flag.conflicts
         args[--brew]=1
         shift
         ;;
 
       # :flag.case
       --node | -n)
+        # :flag.conflicts
         args[--node]=1
         shift
         ;;
 
       # :flag.case
       --python | -p)
+        # :flag.conflicts
         args[--python]=1
         shift
         ;;
 
       # :flag.case
       --cargo | -c)
+        # :flag.conflicts
         args[--cargo]=1
         shift
         ;;
 
-      \
-        -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
@@ -1374,15 +1409,18 @@ dot_sync_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
   # :command.whitelist_filter
+  # :command.user_filter
 }
 
 # :command.parse_requirements
 dot_upgrade_parse_requirements() {
   # :command.fixed_flag_filter
-  case "$1" in
+  case "${1:-}" in
     --version | -v)
       version_command
       exit
@@ -1399,15 +1437,15 @@ dot_upgrade_parse_requirements() {
   # :command.dependencies_filter
   # :command.command_filter
   action="upgrade"
-  # :command.required_args_filter
-  # :command.required_flags_filter
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --ref | -r)
-        if [[ $2 ]]; then
+        # :flag.conflicts
+        if [[ -n ${2+x} ]]; then
+          # :flag.validations
           args[--ref]="$2"
           shift
           shift
@@ -1417,15 +1455,15 @@ dot_upgrade_parse_requirements() {
         fi
         ;;
 
-      \
-        -*)
+      -?*)
         printf "invalid option: %s\n" "$key"
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
-        if [[ ! ${args[package]} ]]; then
+        if [[ -z ${args[package]+x} ]]; then
+          # :argument.validations
           args[package]=$1
           shift
         else
@@ -1436,14 +1474,17 @@ dot_upgrade_parse_requirements() {
 
     esac
   done
+  # :command.required_args_filter
+  # :command.required_flags_filter
   # :command.catch_all_filter
   # :command.default_assignments
-  [[ -n ${args[package]} ]] || args[package]="all"
+  [[ -n ${args[package]:-} ]] || args[package]="all"
   # :command.whitelist_filter
   if [[ ! ${args[package]} =~ ^(all|brew|cargo|mac|neovim|nnn|npm|plugins|python)$ ]]; then
     printf "%s\n" "package must be one of: all, brew, cargo, mac, neovim, nnn, npm, plugins, python"
     exit 1
   fi
+  # :command.user_filter
 }
 
 # :command.initialize
@@ -1451,11 +1492,6 @@ initialize() {
   version="1.0.0"
   long_usage=''
   set -e
-
-  if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-    printf "bash version 4 or higher is required\n"
-    exit 1
-  fi
 
   # :src/initialize.sh
   # shellcheck disable=SC2034
@@ -1477,19 +1513,22 @@ initialize() {
       ;;
   esac
 
-  DEFAULT_SHELL="bash"
+  HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-$(brew --prefix)}"
+
+  # Default shell path. This can be set using `dot shell`.
+  DEFAULT_SHELL_PATH="${HOMEBREW_PREFIX}/bin/zsh"
 
   # Common directories
   DOTFILES_DIRECTORY="${HOME}/dotfiles"
   NEOVIM_DIRECTORY="${HOME}/contributing/neovim"
   NEOVIM_INSTALL_DIRECTORY="${HOME}/neovim"
-  LUA_LANGUAGE_SERVER_DIRECTORY="${HOME}/git/lua-language-server"
   NNN_DIRECTORY="${HOME}/git/nnn"
 
   # Python versions to be installed on the system.
   # First version will be the global one
   PYTHON_VERSIONS=(
-    "3.9.7"
+    "3.10.2"
+    "3.9.10"
   )
 
   # Packages file
@@ -1533,13 +1572,14 @@ initialize() {
     "/Applications/kitty.app"
     "/Applications/Docker.app/Contents/MacOS/Docker Desktop.app"
     "/Applications/Postman.app"
+    "/Applications/pgAdmin 4.app"
     "/Applications/MongoDB Compass.app"
     "/System/Applications/Notes.app"
-    "/Applications/Mark Text.app"
     "/System/Applications/Music.app"
     "/System/Applications/Books.app"
+    "/Applications/Microsoft Teams.app"
     "/Applications/Slack.app"
-    "/Applications/Discord.app"
+    "/Applications/Azure VPN Client.app"
   )
 
   setup_required_directories silent
@@ -1547,14 +1587,14 @@ initialize() {
 
 # :command.run
 run() {
-  declare -A args
-  declare -a other_args
-  declare -a input
+  declare -A args=()
+  declare -a other_args=()
+  declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
   if [[ $action == "mac" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       dot_mac_usage
     else
@@ -1562,7 +1602,7 @@ run() {
     fi
 
   elif [[ $action == "link" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       dot_link_usage
     else
@@ -1570,7 +1610,7 @@ run() {
     fi
 
   elif [[ $action == "shell" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       dot_shell_usage
     else
@@ -1578,7 +1618,7 @@ run() {
     fi
 
   elif [[ $action == "setup" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       dot_setup_usage
     else
@@ -1586,7 +1626,7 @@ run() {
     fi
 
   elif [[ $action == "sync" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       dot_sync_usage
     else
@@ -1594,7 +1634,7 @@ run() {
     fi
 
   elif [[ $action == "upgrade" ]]; then
-    if [[ ${args[--help]} ]]; then
+    if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       dot_upgrade_usage
     else
