refactor: upgrade bashly, generate scripts

diff --git a/bin/dotbot b/bin/dotbot
--- a/bin/dotbot
+++ b/bin/dotbot
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.8.0 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n"
+  printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
@@ -27,27 +27,29 @@ dotbot_usage() {
 
   fi
 
-  printf "Usage:\n"
-  printf "  dotbot [command]\n"
-  printf "  dotbot [command] --help | -h\n"
+  printf "%s\n" "Usage:"
+  printf "  dotbot COMMAND\n"
+  printf "  dotbot [COMMAND] --help | -h\n"
   printf "  dotbot --version | -v\n"
   echo
   # :command.usage_commands
-  printf "Commands:\n"
-  echo "  link      symlink dotfiles after backing up the existing ones"
-  echo "  shell     setup the default shell for the current user"
-  echo "  setup     setup a new mac machine the way I like it"
-  echo "  sync      sync lib files with global package list"
-  echo "  upgrade   upgrade packages"
+  printf "%s\n" "Commands:"
+  printf "  %s   symlink dotfiles after backing up the existing ones\n" "link   "
+  printf "  %s   setup the default shell for the current user\n" "shell  "
+  printf "  %s   setup a new mac machine the way I like it\n" "setup  "
+  printf "  %s   sync lib files with global package list\n" "sync   "
+  printf "  %s   upgrade packages\n" "upgrade"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
+    printf "%s\n" "Options:"
+
     # :command.usage_fixed_flags
-    echo "  --help, -h"
+    printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
-    echo "  --version, -v"
+    printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
     echo
 
@@ -66,21 +68,24 @@ dotbot_link_usage() {
 
   fi
 
-  printf "Usage:\n"
-  printf "  dotbot link [options]\n"
+  printf "%s\n" "Usage:"
+  printf "  dotbot link [OPTIONS]\n"
   printf "  dotbot link --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
-    # :command.usage_fixed_flags
-    echo "  --help, -h"
-    printf "    Show this help\n"
-    echo
+    printf "%s\n" "Options:"
+
     # :command.usage_flags
     # :flag.usage
-    echo "  --force, -f"
+    printf "  %s\n" "--force, -f"
     printf "    skip backup for the existing dotfiles\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -101,15 +106,17 @@ dotbot_shell_usage() {
 
   fi
 
-  printf "Usage:\n"
+  printf "%s\n" "Usage:"
   printf "  dotbot shell\n"
   printf "  dotbot shell --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
+    printf "%s\n" "Options:"
+
     # :command.usage_fixed_flags
-    echo "  --help, -h"
+    printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
@@ -128,15 +135,17 @@ dotbot_setup_usage() {
 
   fi
 
-  printf "Usage:\n"
+  printf "%s\n" "Usage:"
   printf "  dotbot setup\n"
   printf "  dotbot setup --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
+    printf "%s\n" "Options:"
+
     # :command.usage_fixed_flags
-    echo "  --help, -h"
+    printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
@@ -155,36 +164,39 @@ dotbot_sync_usage() {
 
   fi
 
-  printf "Usage:\n"
-  printf "  dotbot sync [options]\n"
+  printf "%s\n" "Usage:"
+  printf "  dotbot sync [OPTIONS]\n"
   printf "  dotbot sync --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
-    # :command.usage_fixed_flags
-    echo "  --help, -h"
-    printf "    Show this help\n"
-    echo
+    printf "%s\n" "Options:"
+
     # :command.usage_flags
     # :flag.usage
-    echo "  --brew, -b"
+    printf "  %s\n" "--brew, -b"
     printf "    sync only homebrew packages\n    File: $HOMEBREW_BUNDLE_FILE\n"
     echo
 
     # :flag.usage
-    echo "  --node, -n"
+    printf "  %s\n" "--node, -n"
     printf "    sync only node packages\n    File: $NPM_GLOBAL_PACKAGES\n"
     echo
 
     # :flag.usage
-    echo "  --python, -p"
+    printf "  %s\n" "--python, -p"
     printf "    sync only Python packages\n    File: $PYTHON_GLOBAL_REQUIREMENTS\n"
     echo
 
     # :flag.usage
-    echo "  --cargo, -c"
+    printf "  %s\n" "--cargo, -c"
     printf "    sync only Cargo packages\n    File: $CARGO_GLOBAL_PACKAGES\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -202,27 +214,31 @@ dotbot_upgrade_usage() {
 
   fi
 
-  printf "Usage:\n"
-  printf "  dotbot upgrade [PACKAGE] [options]\n"
+  printf "%s\n" "Usage:"
+  printf "  dotbot upgrade [PACKAGE] [OPTIONS]\n"
   printf "  dotbot upgrade --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
-    printf "Options:\n"
-    # :command.usage_fixed_flags
-    echo "  --help, -h"
-    printf "    Show this help\n"
-    echo
+    printf "%s\n" "Options:"
+
     # :command.usage_flags
     # :flag.usage
-    echo "  --ref, -r REF"
+    printf "  %s\n" "--ref, -r REF"
     printf "    Upgrade to a specific ref (commit/branch/tag). This flag is applicable only\n    when 'PACKAGE' is:\n      - neovim\n"
     echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
     # :command.usage_args
-    printf "Arguments:\n"
+    printf "%s\n" "Arguments:"
 
     # :argument.usage
-    echo "  PACKAGE"
+    printf "  %s\n" "PACKAGE"
     printf "    package to upgrade\n"
     printf "    Allowed: all, brew, cargo, mac, neovim, nnn, npm, plugins, python\n"
     printf "    Default: all\n"
@@ -257,8 +273,8 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
-  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
@@ -273,6 +289,14 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+  fi
+
 }
 
 # :command.user_lib
@@ -707,6 +731,10 @@ upgrade_nnn() { # {{{1
     git checkout "$latest_tag"
     build_nnn
   )
+
+  # https://github.com/jarun/nnn/tree/master/plugins#installation
+  header "Upgrading nnn plugins..."
+  sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)"
 }
 
 upgrade_npm() { # {{{1
@@ -720,8 +748,8 @@ upgrade_plugins() { # {{{1
   header "Upgrading vim plugins..."
   vim +PlugUpgrade +PlugClean +PlugUpdate
 
-  header "Upgrading neovim plugins..."
-  nvim +PackerSync
+  # header "Upgrading neovim plugins..."
+  # nvim +Lazy sync
 
   header "Cleaning and updating tmux plugins..."
   ~/.tmux/plugins/tpm/bin/clean_plugins
@@ -839,6 +867,7 @@ dotbot_link_command() {
   fi
 
   setup_symlinks
+
 }
 
 # :command.function
@@ -860,6 +889,7 @@ dotbot_shell_command() {
 
   header "Switching to '${DEFAULT_SHELL_PATH}' as the default shell..."
   chsh -s "${DEFAULT_SHELL_PATH}"
+
 }
 
 # :command.function
@@ -909,6 +939,7 @@ dotbot_setup_command() {
 
   update_macos_settings
   update_macos_dock
+
 }
 
 # :command.function
@@ -950,6 +981,7 @@ dotbot_sync_command() {
       | awk -F ' ' '{ if(NR % 2 == 1) {print $1} }' \
         > "${CARGO_GLOBAL_PACKAGES}"
   fi
+
 }
 
 # :command.function
@@ -966,34 +998,39 @@ dotbot_upgrade_command() {
     error "Invalid package: $package"
     exit 1
   fi
+
 }
 
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --version | -v)
-      version_command
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --version | -v)
+        version_command
+        exit
+        ;;
 
-    --help | -h)
-      long_usage=yes
-      dotbot_usage
-      exit
-      ;;
+      --help | -h)
+        long_usage=yes
+        dotbot_usage
+        exit
+        ;;
 
-  esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   # :command.command_filter
   action=${1:-}
 
   case $action in
     -*) ;;
 
-    \
-      link)
+    link)
       action="link"
       shift
       dotbot_link_parse_requirements "$@"
@@ -1029,310 +1066,326 @@ parse_requirements() {
       ;;
 
     # :command.command_fallback
+    "")
+      dotbot_usage >&2
+      exit 1
+      ;;
+
     *)
-      dotbot_usage
+      printf "invalid command: %s\n" "$action" >&2
       exit 1
       ;;
 
   esac
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
         ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
 dotbot_link_parse_requirements() {
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --help | -h)
-      long_usage=yes
-      dotbot_link_usage
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dotbot_link_usage
+        exit
+        ;;
 
-  esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   # :command.command_filter
   action="link"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --force | -f)
-        # :flag.conflicts
+
         # :flag.case_no_arg
-        args[--force]=1
+        args['--force']=1
         shift
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
         ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
 dotbot_shell_parse_requirements() {
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --help | -h)
-      long_usage=yes
-      dotbot_shell_usage
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dotbot_shell_usage
+        exit
+        ;;
 
-  esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   # :command.command_filter
   action="shell"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
         ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
 dotbot_setup_parse_requirements() {
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --help | -h)
-      long_usage=yes
-      dotbot_setup_usage
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dotbot_setup_usage
+        exit
+        ;;
 
-  esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   # :command.command_filter
   action="setup"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
         ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
 dotbot_sync_parse_requirements() {
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --help | -h)
-      long_usage=yes
-      dotbot_sync_usage
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dotbot_sync_usage
+        exit
+        ;;
 
-  esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   # :command.command_filter
   action="sync"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --brew | -b)
-        # :flag.conflicts
+
         # :flag.case_no_arg
-        args[--brew]=1
+        args['--brew']=1
         shift
         ;;
 
       # :flag.case
       --node | -n)
-        # :flag.conflicts
+
         # :flag.case_no_arg
-        args[--node]=1
+        args['--node']=1
         shift
         ;;
 
       # :flag.case
       --python | -p)
-        # :flag.conflicts
+
         # :flag.case_no_arg
-        args[--python]=1
+        args['--python']=1
         shift
         ;;
 
       # :flag.case
       --cargo | -c)
-        # :flag.conflicts
+
         # :flag.case_no_arg
-        args[--cargo]=1
+        args['--cargo']=1
         shift
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key"
+        printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
         ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
 dotbot_upgrade_parse_requirements() {
   # :command.fixed_flags_filter
-  case "${1:-}" in
-    --help | -h)
-      long_usage=yes
-      dotbot_upgrade_usage
-      exit
-      ;;
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dotbot_upgrade_usage
+        exit
+        ;;
 
-  esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+      *)
+        break
+        ;;
+
+    esac
+  done
+
   # :command.command_filter
   action="upgrade"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
       # :flag.case
       --ref | -r)
-        # :flag.conflicts
+
         # :flag.case_arg
         if [[ -n ${2+x} ]]; then
-          # :flag.validations
-          args[--ref]="$2"
+
+          args['--ref']="$2"
           shift
           shift
         else
-          printf "%s\n" "--ref requires an argument: --ref, -r REF"
+          printf "%s\n" "--ref requires an argument: --ref, -r REF" >&2
           exit 1
         fi
         ;;
 
       -?*)
-        printf "invalid option: %s\n" "$key"
+        printf "invalid option: %s\n" "$key" >&2
         exit 1
         ;;
 
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        if [[ -z ${args[package]+x} ]]; then
-          # :argument.validations
-          args[package]=$1
+        if [[ -z ${args['package']+x} ]]; then
+
+          args['package']=$1
           shift
         else
-          printf "invalid argument: %s\n" "$key"
+          printf "invalid argument: %s\n" "$key" >&2
           exit 1
         fi
+
         ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
+
   # :command.default_assignments
-  [[ -n ${args[package]:-} ]] || args[package]="all"
+  [[ -n ${args['package']:-} ]] || args['package']="all"
+
   # :command.whitelist_filter
-  if [[ ! ${args[package]} =~ ^(all|brew|cargo|mac|neovim|nnn|npm|plugins|python)$ ]]; then
-    printf "%s\n" "package must be one of: all, brew, cargo, mac, neovim, nnn, npm, plugins, python"
+  if [[ -n ${args['package']} ]] && [[ ! ${args['package']} =~ ^(all|brew|cargo|mac|neovim|nnn|npm|plugins|python)$ ]]; then
+    printf "%s\n" "package must be one of: all, brew, cargo, mac, neovim, nnn, npm, plugins, python" >&2
     exit 1
   fi
-  # :command.user_filter
+
 }
 
 # :command.initialize
@@ -1413,59 +1466,25 @@ initialize() {
   )
 
   setup_required_directories silent
+
 }
 
 # :command.run
 run() {
   declare -A args=()
+  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
-  if [[ $action == "link" ]]; then
-    if [[ ${args[--help]:-} ]]; then
-      long_usage=yes
-      dotbot_link_usage
-    else
-      dotbot_link_command
-    fi
-
-  elif [[ $action == "shell" ]]; then
-    if [[ ${args[--help]:-} ]]; then
-      long_usage=yes
-      dotbot_shell_usage
-    else
-      dotbot_shell_command
-    fi
-
-  elif [[ $action == "setup" ]]; then
-    if [[ ${args[--help]:-} ]]; then
-      long_usage=yes
-      dotbot_setup_usage
-    else
-      dotbot_setup_command
-    fi
-
-  elif [[ $action == "sync" ]]; then
-    if [[ ${args[--help]:-} ]]; then
-      long_usage=yes
-      dotbot_sync_usage
-    else
-      dotbot_sync_command
-    fi
-
-  elif [[ $action == "upgrade" ]]; then
-    if [[ ${args[--help]:-} ]]; then
-      long_usage=yes
-      dotbot_upgrade_usage
-    else
-      dotbot_upgrade_command
-    fi
-
-  elif [[ $action == "root" ]]; then
-    root_command
-  fi
+  case "$action" in
+    "link") dotbot_link_command ;;
+    "shell") dotbot_shell_command ;;
+    "setup") dotbot_setup_command ;;
+    "sync") dotbot_sync_command ;;
+    "upgrade") dotbot_upgrade_command ;;
+  esac
 }
 
 initialize
