dotbot: update using bashly 1.3.8

diff --git a/bin/dotbot b/bin/dotbot
--- a/bin/dotbot
+++ b/bin/dotbot
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.8 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.3.8 (https://bashly.dev)
 # Modifying it manually is not recommended
 
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -26,6 +26,7 @@ dotbot_usage() {
   echo
 
   if [[ -n "$long_usage" ]]; then
+
     printf "%s\n" "Options:"
 
     printf "  %s\n" "--help, -h"
@@ -47,6 +48,7 @@ dotbot_sync_usage() {
   echo
 
   if [[ -n "$long_usage" ]]; then
+
     printf "%s\n" "Options:"
 
     printf "  %s\n" "--brew, -b"
@@ -81,6 +83,7 @@ dotbot_upgrade_usage() {
   echo
 
   if [[ -n "$long_usage" ]]; then
+
     printf "%s\n" "Options:"
 
     printf "  %s\n" "--ref, -r REF"
@@ -379,6 +382,7 @@ dotbot_upgrade_command() {
 }
 
 parse_requirements() {
+  local key
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -454,6 +458,7 @@ parse_requirements() {
 }
 
 dotbot_sync_parse_requirements() {
+  local key
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -573,6 +578,7 @@ dotbot_sync_parse_requirements() {
 }
 
 dotbot_upgrade_parse_requirements() {
+  local key
 
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -693,5 +699,6 @@ run() {
   esac
 }
 
+command_line_args=("$@")
 initialize
-run "$@"
+run "${command_line_args[@]}"
