chore: use production env for bashly

diff --git a/bin/dotbot b/bin/dotbot
--- a/bin/dotbot
+++ b/bin/dotbot
@@ -2,20 +2,15 @@
 # This script was generated by bashly 1.1.0 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
-# :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
   printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
-# :command.master_script
-
-# :command.version_command
 version_command() {
   echo "$version"
 }
 
-# :command.usage
 dotbot_usage() {
   if [[ -n $long_usage ]]; then
     printf "dotbot - Personal tool for managing dotfiles and packages\n"
@@ -32,7 +27,7 @@ dotbot_usage() {
   printf "  dotbot [COMMAND] --help | -h\n"
   printf "  dotbot --version | -v\n"
   echo
-  # :command.usage_commands
+
   printf "%s\n" "Commands:"
   printf "  %s   symlink dotfiles after backing up the existing ones\n" "link   "
   printf "  %s   setup the default shell for the current user\n" "shell  "
@@ -41,11 +36,9 @@ dotbot_usage() {
   printf "  %s   upgrade packages\n" "upgrade"
   echo
 
-  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -56,7 +49,6 @@ dotbot_usage() {
   fi
 }
 
-# :command.usage
 dotbot_link_usage() {
   if [[ -n $long_usage ]]; then
     printf "dotbot link - symlink dotfiles after backing up the existing ones\n"
@@ -73,17 +65,13 @@ dotbot_link_usage() {
   printf "  dotbot link --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_flags
-    # :flag.usage
     printf "  %s\n" "--force, -f"
     printf "    skip backup for the existing dotfiles\n"
     echo
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -91,7 +79,6 @@ dotbot_link_usage() {
   fi
 }
 
-# :command.usage
 dotbot_shell_usage() {
   if [[ -n $long_usage ]]; then
     printf "dotbot shell\n"
@@ -111,11 +98,9 @@ dotbot_shell_usage() {
   printf "  dotbot shell --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -123,7 +108,6 @@ dotbot_shell_usage() {
   fi
 }
 
-# :command.usage
 dotbot_setup_usage() {
   if [[ -n $long_usage ]]; then
     printf "dotbot setup - setup a new mac machine the way I like it\n"
@@ -140,11 +124,9 @@ dotbot_setup_usage() {
   printf "  dotbot setup --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -152,7 +134,6 @@ dotbot_setup_usage() {
   fi
 }
 
-# :command.usage
 dotbot_sync_usage() {
   if [[ -n $long_usage ]]; then
     printf "dotbot sync - sync lib files with global package list\n"
@@ -169,32 +150,25 @@ dotbot_sync_usage() {
   printf "  dotbot sync --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_flags
-    # :flag.usage
     printf "  %s\n" "--brew, -b"
     printf "    sync only homebrew packages\n    File: $HOMEBREW_BUNDLE_FILE\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--node, -n"
     printf "    sync only node packages\n    File: $NPM_GLOBAL_PACKAGES\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--python, -p"
     printf "    sync only Python packages\n    File: $PYTHON_GLOBAL_REQUIREMENTS\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--cargo, -c"
     printf "    sync only Cargo packages\n    File: $CARGO_GLOBAL_PACKAGES\n"
     echo
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -202,7 +176,6 @@ dotbot_sync_usage() {
   fi
 }
 
-# :command.usage
 dotbot_upgrade_usage() {
   if [[ -n $long_usage ]]; then
     printf "dotbot upgrade - upgrade packages\n"
@@ -219,25 +192,19 @@ dotbot_upgrade_usage() {
   printf "  dotbot upgrade --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_flags
-    # :flag.usage
     printf "  %s\n" "--ref, -r REF"
     printf "    Upgrade to a specific ref (commit/branch/tag). This flag is applicable only\n    when 'PACKAGE' is:\n      - neovim\n"
     echo
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
-    # :command.usage_args
     printf "%s\n" "Arguments:"
 
-    # :argument.usage
     printf "  %s\n" "PACKAGE"
     printf "    package to upgrade\n"
     printf "    Allowed: all, brew, cargo, mac, neovim, nnn, npm, plugins, python\n"
@@ -247,7 +214,6 @@ dotbot_upgrade_usage() {
   fi
 }
 
-# :command.normalize_input
 normalize_input() {
   local arg flags
 
@@ -271,7 +237,7 @@ normalize_input() {
     shift
   done
 }
-# :command.inspect_args
+
 inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
@@ -299,8 +265,6 @@ inspect_args() {
 
 }
 
-# :command.user_lib
-# src/lib/colors.sh
 # ---
 # Color functions
 # This file is a part of Bashly standard library
@@ -334,7 +298,6 @@ blue_underlined() { printf "\e[4;34m%b\e[0m\n" "$*"; }
 magenta_underlined() { printf "\e[4;35m%b\e[0m\n" "$*"; }
 cyan_underlined() { printf "\e[4;36m%b\e[0m\n" "$*"; }
 
-# src/lib/log.sh
 # Helper functions to log to stdout with colors and indicators.
 
 header() {
@@ -349,7 +312,6 @@ warning() {
   yellow_bold "[!] $1"
 }
 
-# src/lib/setup.sh
 declare -a PY_NEOVIM_PACKAGES=(
   "pynvim"
   "debugpy"
@@ -637,7 +599,6 @@ setup_tmux_plugins() { # {{{1
 
 # }}}1
 
-# src/lib/upgrade.sh
 upgrade_all() { # {{{1
   upgrade_brew
   upgrade_plugins
@@ -771,7 +732,6 @@ upgrade_python() { # {{{1
 
 # }}}1
 
-# src/lib/utils.sh
 ask() { # {{{1
   yellow_bold "[?] $1"
   read -r -p "$(bold "> ")"
@@ -839,10 +799,7 @@ setup_required_directories() { # {{{1
 
 # }}}1
 
-# :command.command_functions
-# :command.function
 dotbot_link_command() {
-  # src/link_command.sh
   # shellcheck disable=SC2154
   force=${args[--force]}
 
@@ -870,9 +827,7 @@ dotbot_link_command() {
 
 }
 
-# :command.function
 dotbot_shell_command() {
-  # src/shell_command.sh
   # Setup the default shell as mentioned in the DEFAULT_SHELL_PATH global
   # variable. This will be skipped if the shell is already the default one.
 
@@ -892,9 +847,7 @@ dotbot_shell_command() {
 
 }
 
-# :command.function
 dotbot_setup_command() {
-  # src/setup_command.sh
   seek_confirmation "'setup' command should only be invoked on a fresh setup"
   if ! is_confirmed; then
     exit
@@ -942,9 +895,7 @@ dotbot_setup_command() {
 
 }
 
-# :command.function
 dotbot_sync_command() {
-  # src/sync_command.sh
   # shellcheck disable=SC2154
   sync_brew=${args[--brew]}
   sync_node=${args[--node]}
@@ -984,9 +935,7 @@ dotbot_sync_command() {
 
 }
 
-# :command.function
 dotbot_upgrade_command() {
-  # src/upgrade_command.sh
   # shellcheck disable=SC2154
   package="${args[package]}"
   ref="${args[--ref]}"
@@ -1001,9 +950,8 @@ dotbot_upgrade_command() {
 
 }
 
-# :command.parse_requirements
 parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --version | -v)
@@ -1024,7 +972,6 @@ parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action=${1:-}
 
   case $action in
@@ -1065,7 +1012,6 @@ parse_requirements() {
       shift $#
       ;;
 
-    # :command.command_fallback
     "")
       dotbot_usage >&2
       exit 1
@@ -1078,7 +1024,6 @@ parse_requirements() {
 
   esac
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -1089,8 +1034,7 @@ parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -1101,9 +1045,8 @@ parse_requirements() {
 
 }
 
-# :command.parse_requirements
 dotbot_link_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -1119,17 +1062,14 @@ dotbot_link_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="link"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
+
       --force | -f)
 
-        # :flag.case_no_arg
         args['--force']=1
         shift
         ;;
@@ -1140,8 +1080,7 @@ dotbot_link_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -1152,9 +1091,8 @@ dotbot_link_parse_requirements() {
 
 }
 
-# :command.parse_requirements
 dotbot_shell_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -1170,10 +1108,8 @@ dotbot_shell_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="shell"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -1184,8 +1120,7 @@ dotbot_shell_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -1196,9 +1131,8 @@ dotbot_shell_parse_requirements() {
 
 }
 
-# :command.parse_requirements
 dotbot_setup_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -1214,10 +1148,8 @@ dotbot_setup_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="setup"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -1228,8 +1160,7 @@ dotbot_setup_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -1240,9 +1171,8 @@ dotbot_setup_parse_requirements() {
 
 }
 
-# :command.parse_requirements
 dotbot_sync_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -1258,41 +1188,80 @@ dotbot_sync_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
+  if command -v awk > /dev/null 2>&1; then
+    deps['awk']="$(command -v awk | head -n1)"
+  else
+    printf "missing dependency: awk\n" >&2
+    printf "%s\n" "install with $(green brew install awk)" >&2
+    exit 1
+  fi
+
+  if command -v brew > /dev/null 2>&1; then
+    deps['brew']="$(command -v brew | head -n1)"
+  else
+    printf "missing dependency: brew\n" >&2
+    printf "%s\n" "visit $(blue_underlined https://brew.sh/) to install" >&2
+    exit 1
+  fi
+
+  if command -v cargo > /dev/null 2>&1; then
+    deps['cargo']="$(command -v cargo | head -n1)"
+  else
+    printf "missing dependency: cargo\n" >&2
+    printf "%s\n" "visit $(blue_underlined https://rustup.rs/) to install" >&2
+    exit 1
+  fi
+
+  if command -v jq > /dev/null 2>&1; then
+    deps['jq']="$(command -v jq | head -n1)"
+  else
+    printf "missing dependency: jq\n" >&2
+    printf "%s\n" "install with $(green brew install jq)" >&2
+    exit 1
+  fi
+
+  if command -v npm > /dev/null 2>&1; then
+    deps['npm']="$(command -v npm | head -n1)"
+  else
+    printf "missing dependency: npm\n" >&2
+    printf "%s\n" "install with $(green brew install node)" >&2
+    exit 1
+  fi
+
+  if command -v pipx > /dev/null 2>&1; then
+    deps['pipx']="$(command -v pipx | head -n1)"
+  else
+    printf "missing dependency: pipx\n" >&2
+    printf "%s\n" "install with $(green python -m pip install pipx)" >&2
+    exit 1
+  fi
+
   action="sync"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
+
       --brew | -b)
 
-        # :flag.case_no_arg
         args['--brew']=1
         shift
         ;;
 
-      # :flag.case
       --node | -n)
 
-        # :flag.case_no_arg
         args['--node']=1
         shift
         ;;
 
-      # :flag.case
       --python | -p)
 
-        # :flag.case_no_arg
         args['--python']=1
         shift
         ;;
 
-      # :flag.case
       --cargo | -c)
 
-        # :flag.case_no_arg
         args['--cargo']=1
         shift
         ;;
@@ -1303,8 +1272,7 @@ dotbot_sync_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -1315,9 +1283,8 @@ dotbot_sync_parse_requirements() {
 
 }
 
-# :command.parse_requirements
 dotbot_upgrade_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -1333,17 +1300,14 @@ dotbot_upgrade_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="upgrade"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
+
       --ref | -r)
 
-        # :flag.case_arg
         if [[ -n ${2+x} ]]; then
 
           args['--ref']="$2"
@@ -1361,8 +1325,7 @@ dotbot_upgrade_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         if [[ -z ${args['package']+x} ]]; then
 
           args['package']=$1
@@ -1377,10 +1340,8 @@ dotbot_upgrade_parse_requirements() {
     esac
   done
 
-  # :command.default_assignments
   [[ -n ${args['package']:-} ]] || args['package']="all"
 
-  # :command.whitelist_filter
   if [[ -n ${args['package']} ]] && [[ ! ${args['package']} =~ ^(all|brew|cargo|mac|neovim|nnn|npm|plugins|python)$ ]]; then
     printf "%s\n" "package must be one of: all, brew, cargo, mac, neovim, nnn, npm, plugins, python" >&2
     exit 1
@@ -1388,13 +1349,11 @@ dotbot_upgrade_parse_requirements() {
 
 }
 
-# :command.initialize
 initialize() {
   version="1.0.0"
   long_usage=''
   set -e
 
-  # src/initialize.sh
   # shellcheck disable=SC2034
   #
   # Code here runs inside the `initialize()` function
@@ -1428,8 +1387,11 @@ initialize() {
   # Python versions to be installed on the system.
   # First version will be the global one
   PYTHON_VERSIONS=(
-    "3.10.2"
-    "3.9.10"
+    "3.12.0"
+    "3.11.5"
+    "3.10.13"
+    "3.9.18"
+    "3.8.18"
   )
 
   # Packages file
@@ -1469,7 +1431,6 @@ initialize() {
 
 }
 
-# :command.run
 run() {
   declare -A args=()
   declare -A deps=()
