Update prompt to use PROMPT_COMMAND

diff --git a/bash/bash_prompt b/bash/bash_prompt
--- a/bash/bash_prompt
+++ b/bash/bash_prompt
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 
-prompt_git() {
+function __git_prompt() {
 	local s='';
-	local branchName='';
+	local branch_name='';
 
 	# Check if the current directory is in a Git repository.
 	git rev-parse --is-inside-work-tree &>/dev/null || return;
@@ -12,7 +12,7 @@ prompt_git() {
 	# Get the short symbolic ref. If HEAD isn’t a symbolic ref, get a
 	# tracking remote branch or tag. Otherwise, get the
 	# short SHA for the latest commit, or give up.
-	branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
+	branch_name="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
 		git describe --all --exact-match HEAD 2> /dev/null || \
 		git rev-parse --short HEAD 2> /dev/null || \
 		echo '(unknown)')";
@@ -20,8 +20,8 @@ prompt_git() {
 	# Early exit for Chromium & Blink repo, as the dirty check takes too long.
 	# Thanks, @paulirish!
 	# https://github.com/paulirish/dotfiles/blob/dd33151f/.bash_prompt#L110-L123
-	repoUrl="$(git config --get remote.origin.url)";
-	if grep -q 'chromium/src.git' <<< "${repoUrl}"; then
+	repo_url="$(git config --get remote.origin.url)";
+	if grep -q 'chromium/src.git' <<< "${repo_url}"; then
 		s+='*';
 	else
 		# Check for uncommitted changes in the index.
@@ -47,58 +47,59 @@ prompt_git() {
 
 	[ -n "${s}" ] && s=" [${s}]";
 
-	echo -e "${1}${branchName}${2}${s}";
+	echo -e "${1}${branch_name}${2}${s}";
 }
 
-bold='';
-reset="\e[0m";
-# black="\e[0;30m";
-blue="\e[0;34m";
-# cyan="\e[0;36m";
-green="\e[0;32m";
-orange="\e[0;33m";
-# purple="\e[1;35m";
-red="\e[0;31m";
-violet="\e[0;35m";
-white="\e[1;37m";
-yellow="\e[1;33m";
 
-# Highlight the user name when logged in as root.
-if [[ "${USER}" == "root" ]]; then
-	userStyle="${red}";
-else
-	userStyle="${orange}";
-fi;
+function __build_prompt() {
+  local EXIT="$?"
 
-# Highlight the hostname when connected via SSH.
-if [[ "${SSH_TTY}" ]]; then
-	hostStyle="${bold}${red}";
-else
-	# shellcheck disable=SC2034
-	hostStyle="${yellow}";
-fi;
+  local -r RESET="\[\e[0m\]";
+  local -r RED="\[\e[0;31m\]";
+  local -r GREEN="\[\e[0;32m\]";
+  local -r YELLOW="\[\e[0;33m\]";
+  local -r BLUE="\[\e[1;34m\]";
+  local -r WHITE="\[\e[1;37m\]";
 
-# Set the terminal title and prompt.
-PS1="\[\033]0;\u@\h: \w\007\]"; # title - username@hostname: full working directory
-PS1+="\\[${bold}\\]\\n"; # newline
-PS1+="\\[${blue}\\]\\t: ";  # time
+  PS1="\n"
+  
+  # Prompt - [exitcode] [(root)] [@hostname] pwd [on branch [status]]
+  # Show the exit code if it is not 0
+  if [[ $EXIT -ne 0 ]]; then
+    PS1+="${RED}✗ ${EXIT} "
+  fi
 
-# show username only if its root
-if [[ ${USER} == "root" ]]; then
-	PS1+="\\[${userStyle}\\]\\u";
-    # show hostname only if it's not local
-    if [[ "${SSH_TTY}" ]]; then
-        PS1+="\[${white}\] at ";
-        PS1+="\[${hostStyle}\]\h";
-    fi
-	PS1+="\\[${white}\\] in ";
-fi
+  # PS1+="${BLUE}\t: "
 
-PS1+="\\[${green}\\]\\w"; # working directory full path
-PS1+="\$(prompt_git \"\[${white}\] on \[${violet}\]\" \"\[${blue}\]\")"; # Git repository details
-PS1+="\\n";
-PS1+="\\[${white}\\]\$ \\[${reset}\\]"; # `$` (and reset color)
-export PS1;
+  # Show username only if its root
+  if [[ $USER == "root" ]]; then
+    PS1+="${WHITE}(${RED}\u${WHITE}) "
+  fi
 
-PS2="\\[${yellow}\\]→ \\[${reset}\\]";
-export PS2;
+  # Show hostname only if its not local
+  if [[ "${SSH_TTY}" ]]; then
+    PS1+="${WHITE}@${BLUE}\h "
+  fi
+
+  # Working directory full path
+  PS1+="${GREEN}\w"
+
+  # Git repository details
+  PS1+="\$(__git_prompt \"${WHITE} on ${YELLOW}\" \"${BLUE}\")";
+
+  # Prompt character '$ '
+  PS1+="\n${WHITE}\$ ${RESET}"
+
+  # Continuition prompt
+  PS2="\[${YELLOW}\]→ \[${RESET}\]";
+
+  # Debug prompt
+  PS4="\[${WHITE}\]==> \[${RESET}\]";
+
+}
+
+
+# Set the various prompt commands (PS1, PS2, PS4)
+# Include previous values to maintain Apple Terminal support (window title path and sessions)
+# This is explained in /etc/bashrc_Apple_Terminal
+PROMPT_COMMAND="__build_prompt${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
